const express = require('express');
const docentesRouter = express.Router();

const docentes = [
  {
    "cargo": "Professor Titular",
    "cpf": "123.456.789-10",
    "data-admissao": "01/02/2020",
    "digito-siape": "456",
    "email": "henriquemartinelli31@gmail.com",
    "id-ativo": 1,
    "id-cargo": 2,
    "id-docente": 456,
    "id-institucional": 567,
    "id-situacao": 1,
    "id-unidade": 3,
    "nome": "Henrique Martinelli",
    "nome-identificacao": "Prof. Henrique",
    "regime-trabalho": 20,
    "sexo": "Masculino",
    "siape": 789,
    "siglas-niveis": [{ "sigla-nivel": "GR" }],
    "unidade": "Matemática Avançada"
  },
  {
    "cargo": "Professor Associado",
    "cpf": "234.567.890-11",
    "data-admissao": "15/03/2019",
    "digito-siape": "457",
    "email": "professor_historico@email.com",
    "id-ativo": 1,
    "id-cargo": 3,
    "id-docente": 457,
    "id-institucional": 578,
    "id-situacao": 1,
    "id-unidade": 4,
    "nome": "Carlos Historico",
    "nome-identificacao": "Prof. Carlos",
    "regime-trabalho": 40,
    "sexo": "Masculino",
    "siape": 790,
    "siglas-niveis": [{ "sigla-nivel": "GR" }],
    "unidade": "História Clássica"
  },
  {
    "cargo": "Professor Adjunto",
    "cpf": "345.678.901-12",
    "data-admissao": "10/01/2018",
    "digito-siape": "458",
    "email": "professor_fisica@email.com",
    "id-ativo": 1,
    "id-cargo": 4,
    "id-docente": 458,
    "id-institucional": 589,
    "id-situacao": 1,
    "id-unidade": 5,
    "nome": "João Físico",
    "nome-identificacao": "Prof. João",
    "regime-trabalho": 20,
    "sexo": "Masculino",
    "siape": 791,
    "siglas-niveis": [{ "sigla-nivel": "GR" }],
    "unidade": "Física Aplicada"
  },
  {
    "cargo": "Professor Assistente",
    "cpf": "456.789.012-13",
    "data-admissao": "05/06/2017",
    "digito-siape": "459",
    "email": "professor_quimica@email.com",
    "id-ativo": 1,
    "id-cargo": 5,
    "id-docente": 459,
    "id-institucional": 590,
    "id-situacao": 1,
    "id-unidade": 6,
    "nome": "Ana Química",
    "nome-identificacao": "Prof. Ana",
    "regime-trabalho": 40,
    "sexo": "Feminino",
    "siape": 792,
    "siglas-niveis": [{ "sigla-nivel": "GR" }],
    "unidade": "Química Orgânica"
  },
  {
    "cargo": "Professor Visitante",
    "cpf": "567.890.123-14",
    "data-admissao": "12/09/2021",
    "digito-siape": "460",
    "email": "professor_biologia@email.com",
    "id-ativo": 1,
    "id-cargo": 6,
    "id-docente": 460,
    "id-institucional": 591,
    "id-situacao": 1,
    "id-unidade": 7,
    "nome": "Bianca Biologia",
    "nome-identificacao": "Prof. Bianca",
    "regime-trabalho": 30,
    "sexo": "Feminino",
    "siape": 793,
    "siglas-niveis": [{ "sigla-nivel": "GR" }],
    "unidade": "Biologia Molecular"
  },
  {
    "cargo": "Professor Assistente",
    "cpf": "678.901.234-15",
    "data-admissao": "20/11/2016",
    "digito-siape": "461",
    "email": "professor_engenharia@email.com",
    "id-ativo": 1,
    "id-cargo": 7,
    "id-docente": 461,
    "id-institucional": 592,
    "id-situacao": 1,
    "id-unidade": 8,
    "nome": "Eduardo Engenharia",
    "nome-identificacao": "Prof. Eduardo",
    "regime-trabalho": 40,
    "sexo": "Masculino",
    "siape": 794,
    "siglas-niveis": [{ "sigla-nivel": "GR" }],
    "unidade": "Engenharia Civil"
  },
  {
    "cargo": "Professor Adjunto",
    "cpf": "789.012.345-16",
    "data-admissao": "11/02/2015",
    "digito-siape": "462",
    "email": "professor_filosofia@email.com",
    "id-ativo": 1,
    "id-cargo": 8,
    "id-docente": 462,
    "id-institucional": 593,
    "id-situacao": 1,
    "id-unidade": 9,
    "nome": "Fernando Filosofia",
    "nome-identificacao": "Prof. Fernando",
    "regime-trabalho": 20,
    "sexo": "Masculino",
    "siape": 795,
    "siglas-niveis": [{ "sigla-nivel": "GR" }],
    "unidade": "Filosofia Moderna"
  },
  {
    "cargo": "Professor Titular",
    "cpf": "890.123.456-17",
    "data-admissao": "25/04/2014",
    "digito-siape": "463",
    "email": "professor_sociologia@email.com",
    "id-ativo": 1,
    "id-cargo": 9,
    "id-docente": 463,
    "id-institucional": 594,
    "id-situacao": 1,
    "id-unidade": 10,
    "nome": "Sofia Sociologia",
    "nome-identificacao": "Prof. Sofia",
    "regime-trabalho": 40,
    "sexo": "Feminino",
    "siape": 796,
    "siglas-niveis": [{ "sigla-nivel": "GR" }],
    "unidade": "Sociologia Aplicada"
  },
  {
    "cargo": "Professor Assistente",
    "cpf": "901.234.567-18",
    "data-admissao": "13/08/2013",
    "digito-siape": "464",
    "email": "professor_geografia@email.com",
    "id-ativo": 1,
    "id-cargo": 10,
    "id-docente": 464,
    "id-institucional": 595,
    "id-situacao": 1,
    "id-unidade": 11,
    "nome": "Gabriel Geografia",
    "nome-identificacao": "Prof. Gabriel",
    "regime-trabalho": 30,
    "sexo": "Masculino",
    "siape": 797,
    "siglas-niveis": [{ "sigla-nivel": "GR" }],
    "unidade": "Geografia Humana"
  },
  {
    "cargo": "Professor Associado",
    "cpf": "012.345.678-19",
    "data-admissao": "07/05/2012",
    "digito-siape": "465",
    "email": "professor_quimica_avancada@email.com",
    "id-ativo": 1,
    "id-cargo": 11,
    "id-docente": 465,
    "id-institucional": 596,
    "id-situacao": 1,
    "id-unidade": 12,
    "nome": "Mariana Química",
    "nome-identificacao": "Prof. Mariana",
    "regime-trabalho": 40,
    "sexo": "Feminino",
    "siape": 798,
    "siglas-niveis": [{ "sigla-nivel": "GR" }],
    "unidade": "Química Avançada"
  }
];


docentesRouter.get('/docentes/:idDocente', (req, res) => {
  const { idDocente } = req.params;
  const docente = docentes.find(doc => doc['id-docente'] == idDocente);
  console.log(docente);
  console.log("teste")
  if (docente) {
    res.status(200).json(docente);
  } else {
    res.status(404).json({ message: 'Docente não encontrado' });
  }
});

module.exports = docentesRouter;